config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :questions
  get 'signup1', to: 'students#new'
  resources :students, except: [:new]
  get 'signup2', to: 'teachers#new'
  resources :teachers, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'myquestions', to: 'questions#index1'
  get 'unanswered', to: 'questions#unanswered'
  get 'login2', to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  delete 'logout2', to: 'sessions#destroy2'
  resources :topics, except: [:destroy]
  get 'dashboard', to: "pages#stats"
  get 'pages/update', to: 'pages#update'
  post 'questions/index2', to: 'questions#index2'

end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3,maximum: 25}
    validates_uniqueness_of :name
    has_many :question_topics
    has_many :questions, through: :question_topics
    has_many :student_topics
    has_many :students, through: :student_topics
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def show
        @topic = Topic.find(params[:id])
        @questions = @topic.questions.paginate(page: params[:page], per_page: 3)
    end
    def new 
        @topic = Topic.new
    end
    def index
        @topics = Topic.paginate(page: params[:page], per_page: 3)
    end
    def create
        @topic = Topic.new(topic_params)
        if @topic.save
            flash[:notice] = "Topic created Successfully"
            redirect_to topics_path
        else
            render 'new'
        end

    end
    def edit
        @topic = Topic.find(params[:id])
    end
    def update
        @topic = Topic.find(params[:id])
        if @topic.update(topic_params)
            flash[:notice] = "Topic name updated successfully"
            redirect_to @topic
        else
            render 'edit'
        end
    end
    private
    def topic_params
        params.require(:topic).permit(:name)
    end
    def require_admin
        if !(logged_in_as_student? && current_student.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to topics_path
        end
    end
end

app/views/topics/_form.html.erb
<%= render 'shared/errors', obj: @topic %>
<%= form_with(model: @topic, class: "shadow p-3 mb-3 bg-info rounded",local: true ) do |f| %>
    <div class="form-group row">
        <%= f.label :name, "Topic name", class: "col-2 col-form-label text-light"%> 
        <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name"%>
        </div>
    </div>
    

    <div class="form-group row justify-content-center">
        <%= f.submit class:"btn btn-outline-light btn-lg"%>
    </div>
<% end %>

app/views/topics/_topic.html.erb
<%= link_to topic.name, topic_path(topic), class: "badge badge-pill badge-info mr-1" %>

app/views/topics/edit.html.erb
<h1 class="text-center mt-4">Edit Topic name</h1>

<div class="container">
    
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'form' %>
        </div>
        <div class="mb-3">
            <%= link_to '[ redirecting to topics page ]', topic_path(@topic), class: "text-info"%>
        </div>
    </div>
</div>

app/views/topics/index.html.erb
<h1 class="text-center mt-4">Topics</h1>

<div class="flickr_pagination">
    <%= will_paginate @topics, :container => false %>
</div>

<div class="container">
    <div class="row justify-content-md-center">
        <% @topics.each do |topic| %>     
                <div class="col-4 mt-4">
                    <div class="card text-center shadow mb-5 bg-white rounded">
                        <div class="mt-4 text-center card-img-top">
                            <%= image_tag("topics/#{topic.name.downcase}.jpg", class: "rounded mx-auto d-block center", :size => "250x180")%>
                        </div>  
                        <div class="card-body">

                            <h5 class="card-title"><%= link_to topic.name, topic_path(topic), class: "text-success" %></h5>
                            <p class="card-text"><%= pluralize(topic.questions.count, "questions") %></p>
                        </div>
                        
                    </div>
                </div>
        <% end%>
    </div>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @topics, :container => false %>
</div>

app/views/topics/new.html.erb
<h1 class="text-center mt-4">Create a new Topic</h1>

<div class="container">
    
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'form' %>
        </div>
        <div class="mb-3">
            <%= link_to '[ redirecting to topics page ]', topics_path, class: "text-info"%>
        </div>
    </div>
</div>

app/views/topics/show.html.erb
<h1 class="text-center mt-4"><%= @topic.name%> </h1>

<% if logged_in_as_student? && current_student.admin? %>
    <div class="text-center mt-3 mb-3">
        <%= link_to "Edit topic name", edit_topic_path(@topic), class: "btn btn-outline-info" %>
    </div>
<% end %>
<% if logged_in_as_student? %>

    <div class="container text-center">
        <% x =  StudentTopic.find_by(student_id: current_student.id, topic_id: @topic.id).nil? ? "Follow" : "Unfollow"%>
        <% y =  StudentTopic.find_by(student_id: current_student.id, topic_id: @topic.id).nil? ? "btn-primary" : "btn-dark"%>
        <%= link_to x, { controller: 'pages', action: 'update', remote: true, s_id: current_student.id, t_id: @topic.id, x1: x }, class: "btn #{y}", id: "follow-btn" %>
    </div>
    
<% end %>

<h4 class="text-center mt-4">Question related to this topic</h4>

<div class="flickr_pagination">
    <%= will_paginate @questions, :container => false %>
</div>

<%= render 'questions/question' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @questions, :container => false %>
</div>