config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :questions
  get 'signup1', to: 'students#new'
  resources :students, except: [:new]
  get 'signup2', to: 'teachers#new'
  resources :teachers, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'myquestions', to: 'questions#index1'
  get 'unanswered', to: 'questions#unanswered'
  get 'login2', to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  delete 'logout2', to: 'sessions#destroy2'
  resources :topics, except: [:destroy]
  get 'dashboard', to: "pages#stats"
  get 'pages/update', to: 'pages#update'
  post 'questions/index2', to: 'questions#index2'

end

app/models/teacher.rb
class Teacher < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :questions 
    validates :name, presence: true, 
                     uniqueness: { case_sensitive: false }, 
                     length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      uniqueness: { case_sensitive: false },   
                      length: { maximum: 105},
                      format: { with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :set_teacher, only: [:show,:edit,:update,:destroy]
    before_action :require_teacher, only: [:edit, :update]
    before_action :require_same_teacher, only: [:edit, :update, :destroy]
    def show
        @questions = @teacher.questions.order('created_at DESC').paginate(page: params[:page], per_page: 4)
    end

    def index
        @teachers = Teacher.order('created_at DESC').paginate(page: params[:page], per_page: 6)
    end

    def new
        @teacher = Teacher.new
    end

    def edit
    end

    def update
        if @teacher.update(teacher_params)
           flash[:notice] = "Your account information was successfully updated."
           redirect_to teacher_path(@teacher)
        else 
            render 'edit'
        end 
    end

    def create
        @teacher = Teacher.new(teacher_params)
        if @teacher.save
            session[:teacher_id] = @teacher.id
            flash[:notice] = "Hi #{@teacher.name}, Welcome to doubts solver, you have successfully signed up."
            redirect_to questions_path
        else
            render 'new'
        end
    end

    def destroy
        @teacher.destroy
        session[:teacher_id] = nil if @teacher == current_teacher
        flash[:notice] = "Account and all associated questions were deleted"
        redirect_to questions_path
    end

    private
    def teacher_params
        params.require(:teacher).permit(:name, :email, :password)
    end

    def set_teacher
        if Teacher.where(id:params[:id]) == []
            flash[:alert] = "Oops the account was deleted"
            redirect_to root_path
        else
            @teacher = Teacher.find(params[:id])
        end
    end

    def require_same_teacher
        if current_teacher != @teacher
            flash[:alert] = "You can only edit your own account"
            redirect_to @teacher
        end
    end
end

app/views/teachers/_form.html.erb
<div class="container">
    
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @teacher %>
            <%= form_with(model: @teacher, class: "shadow p-3 mb-3 bg-info rounded",local: true ) do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-2 col-form-label text-light"%> 
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a username"%>
                    </div>
                </div>
                
                <div class="form-group row">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %> 
                    <div class="col-10">
                        <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email"%>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %> 
                    <div class="col-10">
                        <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password"%>
                    </div>
                </div>

                <div class="form-group row justify-content-center">
                    <%= f.submit(@teacher.new_record? ? "Sign up" : "Update account", class:"btn btn-outline-light btn-lg")%>
                </div>
            <% end %>
        </div>
        <div class="mb-3">
            <%= link_to '[ redirecting to questions page ]', questions_path, class: "text-info"%>
        </div>
    </div>
</div>

app/views/teachers/_question.html.erb
<div class="container">
    <div class="row justify-content-md-center">
    <% @questions.each do |question| %>
        <% if !question.ans.nil? %>
            <div class="col-6 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded question">
                    <div class="card-header font-italic">
                        Asked by  <%= question.student.name %>
                        <% if !question.ans.nil? %>
                                & Solved by  <%= question.teacher.name %>
                        <% end %>
                        <% if question.topics.any? %>
                            <div class="mt-2"><%= render question.topics %></div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to truncate(question.que, length: 80), question_path(question), class: "text-success" %></h5>
                        <p class="card-text">
                        <% if question.ans.nil? %>
                            Not answered yet!!
                        <% else %>
                            <%= truncate(question.ans, length: 100)%>
                        <% end %>
                        </p>
                        <%= link_to 'View', question_path(question), class: "btn btn-outline-success"%>
                        <% if question.ans.nil? && logged_in_as_teacher? %>
                            <%= link_to 'Answer it!', edit_question_path(question), class: "btn btn-outline-info"%>
                        <% end %>
                        <% if logged_in_as_student? && current_student == question.student %>
                            <%= link_to 'Delete', question_path(question), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you Sure?"}%>
                        <% end %>
                    </div>
                    <% if question.ans.nil? %>
                    <div class="card-footer bg-danger  text-black">
                    <% else %>
                    <div class="card-footer bg-success  text-black">
                    <% end %>
                    <small> posted <%=time_ago_in_words(question.created_at) %> ago,
                        updated <%=time_ago_in_words(question.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        
        <% end %>
    <% end%>
    </div>
</div>

app/views/teachers/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>

<%= render 'form' %>

app/views/teachers/index.html.erb
<h1 class="text-center mt-4">Teachers</h1>

<div class="flickr_pagination">
    <%= will_paginate @teachers, :container => false %>
</div>

<div class="container">
    <div class="row justify-content-md-center">
    <% @teachers.each do |teacher| %>
        <% if teacher.name != 'ramesh' %>
        
            <div class="col-4 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-header font-italic">
                         <%= link_to teacher.name, teacher_path(teacher) %>
                    </div>
                    <div class="card-body">
                        
                        <p class="card-text"><%= pluralize(teacher.questions.count, "question") %> solved</p>
                        <%= link_to 'View profile', teacher_path(teacher), class: "btn btn-outline-success"%>
                        <% if (logged_in_as_teacher? && current_teacher == teacher) || (logged_in_as_student? && current_student.admin?) %>
                            <%= link_to 'Edit profile', edit_teacher_path(teacher), class: "btn btn-outline-info"%>
        
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small> joined <%=time_ago_in_words(teacher.created_at) %> ago,
                        updated <%=time_ago_in_words(teacher.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        
        <% end %>
        
    <% end%>
    </div>
</div>

<div class="flickr_pagination">
    <%= will_paginate @students, :container => false %>
</div>

app/views/teachers/new.html.erb
<h1 class="text-center mt-4">Sign up as teacher for Doubts solver</h1>

<%= render 'form' %>

app/views/teachers/show.html.erb
<% if logged_in_as_teacher? && current_teacher == @teacher %>
    <h1 class="text-center mt-4">Your profile</h1>
<% else %>
    <h1 class="text-center mt-4"><%= @teacher.name%> profile</h1>
<% end %>


<% if logged_in_as_teacher? && current_teacher == @teacher %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_teacher_path(@teacher), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4"> <%= @teacher.questions.count %> questions solved </h3>

<div class="flickr_pagination">
    <%= will_paginate @questions, :container => false %>
</div>

<%= render 'question' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @questions, :container => false %>
</div>