config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :questions
  get 'signup1', to: 'students#new'
  resources :students, except: [:new]
  get 'signup2', to: 'teachers#new'
  resources :teachers, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'myquestions', to: 'questions#index1'
  get 'unanswered', to: 'questions#unanswered'
  get 'login2', to: 'sessions#new2'
  post 'login2', to: 'sessions#create2'
  delete 'logout2', to: 'sessions#destroy2'
  resources :topics, except: [:destroy]
  get 'dashboard', to: "pages#stats"
  get 'pages/update', to: 'pages#update'
  post 'questions/index2', to: 'questions#index2'

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; Sarath Chandra &copy; Chonus</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name,msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div> 
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Doubts Solver", root_path,class: "no-underline", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ml-2">
        <% x = logged_in_as_student? ? "Feed" : "Home" %>
        <%= link_to x , root_path, class: "nav-link" %>
      </li>
      <% if logged_in_as_student? || logged_in_as_teacher? %>
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Teachers', teachers_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Questions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in_as_student? %>
            <%= link_to 'Ask a question', new_question_path, class: "dropdown-item" %>
            <%= link_to 'List my questions', myquestions_path, class: "dropdown-item" %>
          <% end %>
          <% if logged_in_as_teacher? %>
            <%= link_to 'List unanswered questions', unanswered_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to 'List topicwise questions', topics_path, class: "dropdown-item" %>
          <%= link_to 'List all questions', questions_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Topics
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in_as_student? && current_student.admin?%>
                  <%= link_to 'Create a new topic', new_topic_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to 'View topics', topics_path, class: "dropdown-item" %>
          </div>
      </li>
      
      <% if logged_in_as_student? %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_student.admin? %>
                   (Admin) <%= current_student.name %>
                <% else %>
                   (Student) <%= current_student.name %>
                <% end %>
              </a>    
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <% if current_student.admin? %>
                    <%= link_to 'View Dashboard', dashboard_path, class: "dropdown-item" %>
                  <% end %>
                  <%= link_to 'View profile', student_path(current_student), class: "dropdown-item" %>
                  <%= link_to 'Edit profile', edit_student_path(current_student), class: "dropdown-item" %>
                  <%= link_to 'Delete profile', student_path(current_student), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"}%>
              </div>
          </li>
          <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete%>
          </li>
      <% elsif logged_in_as_teacher? %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  (Teacher) <%= current_teacher.name %>
              </a>    
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'View profile', teacher_path(current_teacher), class: "dropdown-item" %>
                  <%= link_to 'Edit profile', edit_teacher_path(current_teacher), class: "dropdown-item" %>
                  <%= link_to 'Delete profile', teacher_path(current_teacher), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"}%>
              </div>
          </li>
          <li class="nav-item">
              <%= link_to "Logout", logout_path, class: "nav-link", method: :delete%>
          </li>
      <% else %>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login
              </a>    
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Login as student', login_path , class: "dropdown-item" %>
                  <%= link_to 'Login as teacher', login2_path, class: "dropdown-item" %>
              </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Signup
              </a>    
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Signup as student', signup1_path , class: "dropdown-item" %>
                  <%= link_to 'Signup as teacher', signup2_path, class: "dropdown-item" %>
              </div>
          </li>     
      <% end %>
    </ul>
    <% if logged_in_as_student? || logged_in_as_teacher? %> 
      <%= form_tag({ controller: "questions", action: "index2" }, method: "post", remote:true, class: "form-inline my-2 my-lg-0") do %>
        <%= text_field_tag(:search, nil, class: "form-control mr-sm-2", placeholder: "Search a question", aria: { label: "Search" }) %>
        <%= submit_tag("Search", class: "btn btn-outline-light my-2 my-sm-0", type: "submit") %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>